language: elixir
elixir:
  - 1.6.4
otp_release:
  - 20.2

env:
  - MIX_ENV=test

script:
  - mix credo --strict
  # Only fails on Travis!
  # - mix format --check-formatted
  - mix test
  - mix coveralls.travis
